name: voiture
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  dio: ^5.8.0
  image_picker: ^1.0.7
  path: ^1.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  
  

flutter:
  uses-material-design: true
  assets: 
    - assets/


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/voiturelogo.jpg"
  adaptive_icon_background: "#000000"